mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-handlers-package: top.zhacker.sample.retail.online.item.domain.mybatis

swagger:
  basePackage: top.zhacker.sample.retail.online.item.rest.item
server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/retail?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: anywhere
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring.cloud.sentinel.transport.dashboard: localhost:15000
spring.cloud.nacos.discovery.server-addr: http://127.0.0.1:8848/nacos


# Eureka config for discovery
eureka.instance.metadataMap.version: 1.0
eureka.instance.metadataMap.group: example-service-group
eureka.instance.metadataMap.region: dev

# Consul config for discovery
spring.cloud.consul.discovery.tags: version=1.0,group=example-service-group,region=dev

# Zookeeper config for discovery
spring.cloud.zookeeper.discovery.metadata.version: 1.0
spring.cloud.zookeeper.discovery.metadata.group: example-service-group
spring.cloud.zookeeper.discovery.metadata.region: dev

# Nacos config for discovery
spring.cloud.nacos.discovery.metadata.version: 1.0
spring.cloud.nacos.discovery.metadata.group: example-service-group
spring.cloud.nacos.discovery.metadata.region: dev