spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/


eureka:
  client:
    service-url:
           defaultZone: http://localhost:8761/eureka


#logging:
#     level:
#       top.zhacker.sample: debug
#       okhttp3: debug
feign:
  hystrix:
    enabled: true
  httpclient:
       enabled: false
  okhttp:
       enabled: true
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000
  compression:
      request:
          enabled: true
          mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
          min-request-size: 204800  # 配置压缩数据大小的下限
      response:
          enabled: true # 配置响应GZIP压缩
sample-provider:
  ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 60000
    MaxAutoRetries: 1 #对第一次请求的服务的重试次数
    MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
    OkToRetryOnAllOperations: true
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: sample-provider

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  command:
    default:
      execution:
        timeout:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
