server:
  port: 8191
spring:
  application:
    name: spring-cloud-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${jwk-url:http://localhost:8181}/.well-known/jwks.json
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: zhacker
        uri: https://www.jianshu.com/u/4bf916ad9230
        predicates:
        - Path=/zhacker
      - id: sample-consumer
        uri: lb://sample-consumer
        predicates:
        - Path=/sample-consumer/**
        filters:
        - StripPrefix=1
      - id: sample-provider
        uri: lb://sample-provider
        predicates:
        - Path=/sample-provider/**
        filters:
        - StripPrefix=1

logging: ## Spring Cloud Gateway的日志配置
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

spring.webflux.hiddenmethod.filter.enabled: false