spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true #内部默认已开启，这里列出来说明这个参数比较重要
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
zuul:
  retryable: true #开启重试，D版之后默认为false，需要手动开启
  ribbon:
    eager-load:
      enabled: false #开启饥饿加载
#  routes:
#    sample-consumer:
#      path: /sample-consumer/**
#      serviceId: sample-consumer
#    sample-provider:
#      path: /sample-provider/**
#      serviceId: sample-provider
  ratelimit:
    key-prefix: zhacker-gateway-zuul #按粒度拆分的临时变量key前缀
    enabled: true #启用开关
    repository: IN_MEMORY #key存储类型，默认是IN_MEMORY本地内存，此外还有多种形式
    behind-proxy: true #表示代理之后
    default-policy: #全局限流策略，可单独细化到服务粒度
      limit: 2 #在一个单位时间窗口的请求数量
      quota: 1 #在一个单位时间窗口的请求时间限制
      refresh-interval: 3 #单位时间窗口
      type:
        - user #可指定用户粒度
        - origin #可指定客户端地址粒度
        - url #可指定url粒度

logging.level.org.springframework.cloud.netflix.zuul: debug

#禁用HttpClient并开启OkHttp
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
#重试机制配置
  ConnectTimeout: 3000
  ReadTimeout: 60000
  MaxAutoRetries: 1 #对第一次请求的服务的重试次数
  MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
  OkToRetryOnAllOperations: true
